environment_variables: {}
external_package_dirs: []
python_version: py39
requirements:
- git+https://github.com/abacaj/ctransformers.git
resources:
  cpu: 3500m
  memory: 3500Mi
  use_gpu: false
secrets: {}
spec_version: '2.0'
system_packages: []
