version: 2.1

orbs:
  slack: circleci/slack@4.1

workflows:
  integration_tests:
    jobs:
      - integration_tests:
          filters:
            branches:
              only:
                - main
                - minfold

commands:

jobs:
  integration_tests:
    working_directory: ~/truss
    machine:
      image: ubuntu-2204:2022.04.2
      resource_class: large
      docker_layer_caching: true
    steps:
      - checkout
      # this updates git-lfs to make pre-commit large files check hook work properly
      # more details in https://github.com/pre-commit/pre-commit-hooks/issues/252
      - run:
          command: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run:
          command: sudo apt-get install git-lfs --upgrade
      - run:
          command: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: git auth
          command: |
            git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
      - run:
          name: install dependencies
          command: |
            pyenv install
            curl -sSL https://install.python-poetry.org | python3 -
            export PATH="/home/circleci/.local/bin:$PATH"
            poetry install
      - run:
          name: 'Integration Tests'
          command: |
            export PATH="/home/circleci/.local/bin:$PATH"
            poetry run pytest truss/tests -m 'integration'
