name: Docker Image CI

on:
  push:
    branches: [ "main", "ph/docker-build-ci" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: baseten/truss:${{ github.sha }}
        cache-from: |
          type=gha, scope=${{ github.workflow }}-${{ github.ref_name }}
        cache-to: type=gha, mode=max, scope=${{ github.workflow }}-${{ github.ref_name }}
