name: ecrpush

on:
  push:
    branches:
      - ecrpush

jobs:

  build-n-push-to-ecr-context-builder-image:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Build docker image
      id: build-image
      run: |
        docker build . -f ./context_builder.Dockerfile -t public.ecr.aws/q8h3f2p1/baseten/truss-context-builder:vpankajtest1
        docker push public.ecr.aws/q8h3f2p1/baseten/truss-context-builder:vpankajtest1
