name: integration-tests

on:
  workflow_dispatch: # Allows running from actions tab
  push:
    branches:
      - pg/sh2

concurrency:
  group: main-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  integration_tests:
    runs-on: truss-runner
    strategy:
      fail-fast: false
      matrix:
        split_group: ["1", "2", "3", "4", "5"]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.11.0
      - uses: ./.github/actions/setup-python/
      - run: poetry install
      - run: poetry run pytest truss/tests -m 'integration' --splits 5 --group ${{ matrix.split_group }}
