name: PR

on:
  pull_request:
    paths:
      - poetry.lock
      - pyproject.yaml
      - "truss/**"
      - "docs/**"
      - .github/workflows/pr.yml

concurrency:
  group: pr-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: ./.github/actions/setup-python/
      - run: poetry install
      - run: poetry run pre-commit run --all-files
        env:
          SKIP: isort,flake8
      - run: poetry run isort **/*.py --check-only
      - run: poetry run flake8 truss

  test:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ["3.8", "3.9.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: ./.github/actions/setup-python/
        with:
          python-version: ${{ matrix.python_version }}
      - run: poetry install
      - name: run tests (poetry run pytest...)
        run: poetry run pytest -v --cov=truss -m 'not integration'

  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: "yes"
          folder-path: "docs"
