# [Deprecated] This happens automatically on merge to main. This workflow will
# be deleted soon.
name: Release CI

on:
  push:
    tags: [ "v*" ]

jobs:
  build-n-push-image:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: baseten/truss-context-builder

    - name: Prep version
      id: prep_version
      run: |
        version=$(poetry version | awk '{print $2}')
        echo ::set-output name=version::$version

    - name: Docker Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./context_builder.Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: baseten/truss-context-builder:v${{steps.prep_version.outputs.version}}dev11
        labels: ${{ steps.meta.outputs.labels }}

  publish-to-pypi:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup-python/

    - name: Install poetry packages
      run: poetry install --no-dev

    - name: Build
      run: poetry build

    - name: Publish to PyPI
      if: ${{ github.event_name != 'pull_request' }}
      run: poetry publish -u "${{ secrets.PYPI_USERNAME }}" -p "${{ secrets.PYPI_PASSWORD }}"
