name: Release CI

on:
  push:
    branches:
      - bola/add-truss-utils-package
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true
        default: 0.1.0

    

concurrency:
  group: release-utils-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Bump version in pyproject.toml
      working-directory: truss-utils
      run: |  
        poetry version $INPUT_VERSION
      env:
        INPUT_VERSION: ${{ github.event.inputs.version }}

  publish-to-pypi:
    needs: [bump_version]
    runs-on: ubuntu-20.04
    steps:
      - name: "Git tag release"
        uses: actions/checkout@v3
        with:
          token: ${{secrets.BASETENBOT_GITHUB_TOKEN}}
      - run: |
          NEW_VERSION=v${{ needs.detect-version-changed.outputs.new_version }}
          git config --global user.name "Github action"
          git config --global user.email "github.action@baseten.co"

          git tag -a $NEW_VERSION -m "Release truss-utils $NEW_VERSION"
          git push origin $NEW_VERSION

      - uses: ./.github/actions/setup-python/

      - name: Install poetry packages
        working-directory: truss-utils
        run: poetry install --no-dev

      - name: Build
        working-directory: truss-utils
        run: poetry build

      - name: Publish to PyPI
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: truss-utils
        run: poetry publish -u "${{ secrets.PYPI_USERNAME }}" -p "${{ secrets.PYPI_PASSWORD }}"
